
-- auto exported game_attributes 
-- including native attributes and custom attributes 


---@enum UGCNativeGameAttributeType
UGCNativeGameAttributeType = { 
	--Character [血量-Health],
	Character_Health = 'Health',
	--Character [最大血量-HealthMax],
	Character_HealthMax = 'HealthMax',
	--Character [技能急速-SkillCDRecoverRate],
	Character_SkillCDRecoverRate = 'SkillCDRecoverRate',
	--Character [信号值-SignalHP],
	Character_SignalHP = 'SignalHP',
	--Character [最大信号值-SignalHPMax],
	Character_SignalHPMax = 'SignalHPMax',
	--Character [声音检查距离(发生端)-voiceCheckDis],
	Character_voiceCheckDis = 'voiceCheckDis',
	--Character [呼吸值-Breath],
	Character_Breath = 'Breath',
	--Character [额外速度值-AdditiveSpeedValueWrapper],
	Character_AdditiveSpeedValueWrapper = 'AdditiveSpeedValueWrapper',
	--Character [当前能量值-EnergyCurrent],
	Character_EnergyCurrent = 'Energy|EnergyCurrent',
	--Character [UGC移动速度倍率-UGCGeneralMoveSpeedScale],
	Character_UGCGeneralMoveSpeedScale = 'UGCGeneralMoveSpeedScale',
	--Character [救援速率-RescueOtherDurationRate],
	Character_RescueOtherDurationRate = 'RescueOtherDurationRate',
	--Character [连跳次数-JumpCountLimit],
	Character_JumpCountLimit = 'JumpCountLimit',
	--Character [跳跃速度-JumpZSpeed],
	Character_JumpZSpeed = 'JumpZSpeed',
	--Character [跌落伤害倍率-FallingDamageRatio],
	Character_FallingDamageRatio = 'FallingDamageRatio',
	--Character [击退强度-HitBackIntensity],
	Character_HitBackIntensity = 'HitBackIntensity',
	--Character [击退抗性-HitBackResist],
	Character_HitBackResist = 'HitBackResist',
	--Character [旋转屏幕灵敏度动态系数Yaw-DynamicTouchMoveScreenSensibilityRateYaw],
	Character_DynamicTouchMoveScreenSensibilityRateYaw = 'DynamicTouchMoveScreenSensibilityRateYaw',
	--Character [旋转屏幕灵敏度动态系数Pitch-DynamicTouchMoveScreenSensibilityRatePitch],
	Character_DynamicTouchMoveScreenSensibilityRatePitch = 'DynamicTouchMoveScreenSensibilityRatePitch',

---------------------------------------------------------

	--Weapon [连发数量-BurstShootBulletsNum],
	Weapon_BurstShootBulletsNum = 'ShootWeaponEntityComp|BurstShootBulletsNum',
	--Weapon [射击前处理（拉栓）时长-PreFireTime],
	Weapon_PreFireTime = 'ShootWeaponEntityComp|PreFireTime',
	--Weapon [射击后处理时长-PostFireTime],
	Weapon_PostFireTime = 'ShootWeaponEntityComp|PostFireTime',
	--Weapon [单发换弹开始动作加第一发子弹时长-ReloadDurationStart],
	Weapon_ReloadDurationStart = 'ShootWeaponEntityComp|ReloadDurationStart',
	--Weapon [单发换弹循环加一发子弹时长-ReloadDurationLoop],
	Weapon_ReloadDurationLoop = 'ShootWeaponEntityComp|ReloadDurationLoop',
	--Weapon [全弹夹换弹时长-ReloadTime],
	Weapon_ReloadTime = 'ShootWeaponEntityComp|ReloadTime',
	--Weapon [全弹夹换弹时间修改参数-ReloadTimeModifier],
	Weapon_ReloadTimeModifier = 'ShootWeaponEntityComp|ReloadTimeModifier',
	--Weapon [战术换弹时长-ReloadTimeTactical],
	Weapon_ReloadTimeTactical = 'ShootWeaponEntityComp|ReloadTimeTactical',
	--Weapon [战术换弹时间修改参数-ReloadTimeTacticalModifier],
	Weapon_ReloadTimeTacticalModifier = 'ShootWeaponEntityComp|ReloadTimeTacticalModifier',
	--Weapon [单发战术换弹时间修改参数-ReloadTimeTacticalOneByOneModifier],
	Weapon_ReloadTimeTacticalOneByOneModifier = 'ShootWeaponEntityComp|ReloadTimeTacticalOneByOneModifier',
	--Weapon [所有换弹时间修改参数-AllReloadTimeModifier],
	Weapon_AllReloadTimeModifier = 'ShootWeaponEntityComp|AllReloadTimeModifier',
	--Weapon [全弹夹换弹开始到拔出弹夹时间-ReloadTimeMagOut],
	Weapon_ReloadTimeMagOut = 'ShootWeaponEntityComp|ReloadTimeMagOut',
	--Weapon [战术换弹开始到拔出弹夹时间-ReloadTimeMagOutTactical],
	Weapon_ReloadTimeMagOutTactical = 'ShootWeaponEntityComp|ReloadTimeMagOutTactical',
	--Weapon [全弹夹换弹时弹夹插入到换弹结束的时间-ReloadTimeMagIn],
	Weapon_ReloadTimeMagIn = 'ShootWeaponEntityComp|ReloadTimeMagIn',
	--Weapon [战术换弹时弹夹插入到换弹结束的时间-ReloadTimeMagInTactical],
	Weapon_ReloadTimeMagInTactical = 'ShootWeaponEntityComp|ReloadTimeMagInTactical',
	--Weapon [垂直后坐力修改参数-VerticalRecoilFactorModifier],
	Weapon_VerticalRecoilFactorModifier = 'ShootWeaponEntityComp|VerticalRecoilFactorModifier',
	--Weapon [水平后坐力修改参数-HorizontalRecoilFactorModifier],
	Weapon_HorizontalRecoilFactorModifier = 'ShootWeaponEntityComp|HorizontalRecoilFactorModifier',
	--Weapon [后坐回正参数-AccessoriesRecoveryFactor],
	Weapon_AccessoriesRecoveryFactor = 'ShootWeaponEntityComp|AccessoriesRecoveryFactor',
	--Weapon [散弹枪垂直散布-ShotGunVerticalSpread],
	Weapon_ShotGunVerticalSpread = 'ShootWeaponEntityComp|ShotGunVerticalSpread',
	--Weapon [散弹枪水平散布-ShotGunHorizontalSpread],
	Weapon_ShotGunHorizontalSpread = 'ShootWeaponEntityComp|ShotGunHorizontalSpread',
	--Weapon [所有散布因子-GameDeviationFactor],
	Weapon_GameDeviationFactor = 'ShootWeaponEntityComp|GameDeviationFactor',
	--Weapon [开镜跳跃散布因子-ScopeJumpDeviationFactor],
	Weapon_ScopeJumpDeviationFactor = 'ShootWeaponEntityComp|ScopeJumpDeviationFactor',
	--Weapon [开镜Falling散布因子-ScopeFallingDeviationFactor],
	Weapon_ScopeFallingDeviationFactor = 'ShootWeaponEntityComp|ScopeFallingDeviationFactor',
	--Weapon [最终散布修改参数-DeviationFactorModifier],
	Weapon_DeviationFactorModifier = 'ShootWeaponEntityComp|DeviationFactorModifier',
	--Weapon [枪械开镜速度-WeaponAimInTime],
	Weapon_WeaponAimInTime = 'ShootWeaponEntityComp|WeaponAimInTime',
	--Weapon [倍镜类别-SightType],
	Weapon_SightType = 'ShootWeaponEntityComp|SightType',
	--Weapon [开镜开火后坐力动画表现系数-RecoilKickADS],
	Weapon_RecoilKickADS = 'ShootWeaponEntityComp|RecoilKickADS',
	--Weapon [开火抖动幅度-AnimationKick],
	Weapon_AnimationKick = 'ShootWeaponEntityComp|AnimationKick',
	--Weapon [UGC换弹时间影响因子-ReloadTimeFactorWrapper],
	Weapon_ReloadTimeFactorWrapper = 'ReloadTimeFactorWrapper',
	--Weapon [UGC切枪时间影响因子-SwitchTimeFactorWrapper],
	Weapon_SwitchTimeFactorWrapper = 'SwitchTimeFactorWrapper',
	--Weapon [UGC攻击间隔影响因子-ShootIntervalFactorWrapper],
	Weapon_ShootIntervalFactorWrapper = 'ShootIntervalFactorWrapper',
	--Weapon [UGC后坐力影响因子-RecoilFactorWrapper],
	Weapon_RecoilFactorWrapper = 'RecoilFactorWrapper',
	--Weapon [UGC散布影响因子-DeviationFactorWrapper],
	Weapon_DeviationFactorWrapper = 'DeviationFactorWrapper',
	--Weapon [UGC子弹基础伤害-BaseImpactDamageWrapper],
	Weapon_BaseImpactDamageWrapper = 'BaseImpactDamageWrapper',
	--Weapon [UGC子弹最低伤害-MinimumImpactDamageWrapper],
	Weapon_MinimumImpactDamageWrapper = 'MinimumImpactDamageWrapper',
	--Weapon [UGC子弹飞行速度-BulletFireSpeedWrapper],
	Weapon_BulletFireSpeedWrapper = 'BulletFireSpeedWrapper',
	--Weapon [UGC最大射程-BulletRangeWrapper],
	Weapon_BulletRangeWrapper = 'BulletRangeWrapper',
	--Weapon [UGC一次拉栓子弹装填数量-MaxBulletNumInBarrelWrapper],
	Weapon_MaxBulletNumInBarrelWrapper = 'MaxBulletNumInBarrelWrapper',
	--Weapon [UGC弹匣容量-MaxBulletNumInOneClipWrapper],
	Weapon_MaxBulletNumInOneClipWrapper = 'MaxBulletNumInOneClipWrapper',
	--Weapon [UGC全自动射击间隔-AutoShootIntervalWrapper],
	Weapon_AutoShootIntervalWrapper = 'AutoShootIntervalWrapper',
	--Weapon [UGC连发射击间隔-BurstShootCDWrapper],
	Weapon_BurstShootCDWrapper = 'BurstShootCDWrapper',
	--Weapon [UGC连发数量-BurstShootBulletsNumWrapper],
	Weapon_BurstShootBulletsNumWrapper = 'BurstShootBulletsNumWrapper',
	--Weapon [UGC连发子弹间隔-BurstShootIntervalWrapper],
	Weapon_BurstShootIntervalWrapper = 'BurstShootIntervalWrapper',

---------------------------------------------------------

	--Vehicle [当前血量-CurrentHP],
	Vehicle_Internal_CurrentHP = 'CurrentHP',
	--Vehicle [最大血量-MaxHP],
	Vehicle_Internal_MaxHP = 'MaxHP',
	--Vehicle [当前油量-CurrentFuel],
	Vehicle_Internal_CurrentFuel = 'CurrentFuel',
	--Vehicle [最大油量-MaxFuel],
	Vehicle_Internal_MaxFuel = 'MaxFuel',
	--Vehicle [耗油系数-FuelConsumeFactor],
	Vehicle_Internal_FuelConsumeFactor = 'FuelConsumeFactor',
	--Vehicle [撞车时对载具冲量吸收-ImpactAbsorption],
	Vehicle_Internal_ImpactAbsorption = 'ImpactAbsorption',
	--Vehicle [撞车时对乘客冲量吸收-ImpactAbsorptionPassenger],
	Vehicle_Internal_ImpactAbsorptionPassenger = 'ImpactAbsorptionPassenger',
	--Vehicle [撞车时对乘客伤害上限-HitDamagePassengerMaxHP],
	Vehicle_Internal_HitDamagePassengerMaxHP = 'HitDamagePassengerMaxHP',
	--Vehicle [载具爆炸基础伤害-ExplosionBaseDamage],
	Vehicle_Internal_ExplosionBaseDamage = 'ExplosionBaseDamage',
	--Vehicle [载具爆炸最小伤害-ExplosionMinimumDamage],
	Vehicle_Internal_ExplosionMinimumDamage = 'ExplosionMinimumDamage',
	--Vehicle [加速油耗系数-FuelConsumptionModifierBoost],
	Vehicle_Internal_FuelConsumptionModifierBoost = 'FuelConsumptionModifierBoost',
	--Vehicle [加速动力系数(不同载具动力表达会有所区别)-BoostModifier],
	Vehicle_Internal_BoostModifier = 'BoostModifier',
	--Vehicle [线性阻尼(影响陆地载具和船)-LinearDamping],
	Vehicle_Internal_LinearDamping = 'LinearDamping',
	--Vehicle [旋转阻尼(影响陆地载具和船)-AngularDamping],
	Vehicle_Internal_AngularDamping = 'AngularDamping',
	--Vehicle [最大加速度(仅影响船载具)-MaxAcceleration],
	Vehicle_Internal_MaxAcceleration = 'MaxAcceleration',
	--Vehicle [加速度增加速率(仅影响船载具)-StartAccelerationRate],
	Vehicle_Internal_StartAccelerationRate = 'StartAccelerationRate',
	--Vehicle [倒车时加速度缩放值(仅影响船载具)-BackwardForceScale],
	Vehicle_Internal_BackwardForceScale = 'BackwardForceScale',
	--Vehicle [最大转向角(仅影响船载具)-MaxRotationYawAngle],
	Vehicle_Internal_MaxRotationYawAngle = 'MaxRotationYawAngle',
	--Vehicle [最大速度限制(0表示无限速，仅影响船载具)-MaxVelocity],
	Vehicle_Internal_MaxVelocity = 'MaxVelocity',
	--Vehicle [撞人基础伤害-HitDamageBase],
	Vehicle_Internal_HitDamageBase = 'HitDamageBase',
}; 

UGCNativeGameAttributeTypeCommentMap = { 

---------------------------------------------------------

	['Health'] = 'Character [血量-Health]', 
	['HealthMax'] = 'Character [最大血量-HealthMax]', 
	['SkillCDRecoverRate'] = 'Character [技能急速-SkillCDRecoverRate]', 
	['SignalHP'] = 'Character [信号值-SignalHP]', 
	['SignalHPMax'] = 'Character [最大信号值-SignalHPMax]', 
	['voiceCheckDis'] = 'Character [声音检查距离(发生端)-voiceCheckDis]', 
	['Breath'] = 'Character [呼吸值-Breath]', 
	['AdditiveSpeedValueWrapper'] = 'Character [额外速度值-AdditiveSpeedValueWrapper]', 
	['Energy|EnergyCurrent'] = 'Character [当前能量值-EnergyCurrent]', 
	['UGCGeneralMoveSpeedScale'] = 'Character [UGC移动速度倍率-UGCGeneralMoveSpeedScale]', 
	['RescueOtherDurationRate'] = 'Character [救援速率-RescueOtherDurationRate]', 
	['JumpCountLimit'] = 'Character [连跳次数-JumpCountLimit]', 
	['JumpZSpeed'] = 'Character [跳跃速度-JumpZSpeed]', 
	['FallingDamageRatio'] = 'Character [跌落伤害倍率-FallingDamageRatio]', 
	['HitBackIntensity'] = 'Character [击退强度-HitBackIntensity]', 
	['HitBackResist'] = 'Character [击退抗性-HitBackResist]', 
	['DynamicTouchMoveScreenSensibilityRateYaw'] = 'Character [旋转屏幕灵敏度动态系数Yaw-DynamicTouchMoveScreenSensibilityRateYaw]', 
	['DynamicTouchMoveScreenSensibilityRatePitch'] = 'Character [旋转屏幕灵敏度动态系数Pitch-DynamicTouchMoveScreenSensibilityRatePitch]', 

---------------------------------------------------------

	['ShootWeaponEntityComp|BurstShootBulletsNum'] = 'Weapon [连发数量-BurstShootBulletsNum]', 
	['ShootWeaponEntityComp|PreFireTime'] = 'Weapon [射击前处理（拉栓）时长-PreFireTime]', 
	['ShootWeaponEntityComp|PostFireTime'] = 'Weapon [射击后处理时长-PostFireTime]', 
	['ShootWeaponEntityComp|ReloadDurationStart'] = 'Weapon [单发换弹开始动作加第一发子弹时长-ReloadDurationStart]', 
	['ShootWeaponEntityComp|ReloadDurationLoop'] = 'Weapon [单发换弹循环加一发子弹时长-ReloadDurationLoop]', 
	['ShootWeaponEntityComp|ReloadTime'] = 'Weapon [全弹夹换弹时长-ReloadTime]', 
	['ShootWeaponEntityComp|ReloadTimeModifier'] = 'Weapon [全弹夹换弹时间修改参数-ReloadTimeModifier]', 
	['ShootWeaponEntityComp|ReloadTimeTactical'] = 'Weapon [战术换弹时长-ReloadTimeTactical]', 
	['ShootWeaponEntityComp|ReloadTimeTacticalModifier'] = 'Weapon [战术换弹时间修改参数-ReloadTimeTacticalModifier]', 
	['ShootWeaponEntityComp|ReloadTimeTacticalOneByOneModifier'] = 'Weapon [单发战术换弹时间修改参数-ReloadTimeTacticalOneByOneModifier]', 
	['ShootWeaponEntityComp|AllReloadTimeModifier'] = 'Weapon [所有换弹时间修改参数-AllReloadTimeModifier]', 
	['ShootWeaponEntityComp|ReloadTimeMagOut'] = 'Weapon [全弹夹换弹开始到拔出弹夹时间-ReloadTimeMagOut]', 
	['ShootWeaponEntityComp|ReloadTimeMagOutTactical'] = 'Weapon [战术换弹开始到拔出弹夹时间-ReloadTimeMagOutTactical]', 
	['ShootWeaponEntityComp|ReloadTimeMagIn'] = 'Weapon [全弹夹换弹时弹夹插入到换弹结束的时间-ReloadTimeMagIn]', 
	['ShootWeaponEntityComp|ReloadTimeMagInTactical'] = 'Weapon [战术换弹时弹夹插入到换弹结束的时间-ReloadTimeMagInTactical]', 
	['ShootWeaponEntityComp|VerticalRecoilFactorModifier'] = 'Weapon [垂直后坐力修改参数-VerticalRecoilFactorModifier]', 
	['ShootWeaponEntityComp|HorizontalRecoilFactorModifier'] = 'Weapon [水平后坐力修改参数-HorizontalRecoilFactorModifier]', 
	['ShootWeaponEntityComp|AccessoriesRecoveryFactor'] = 'Weapon [后坐回正参数-AccessoriesRecoveryFactor]', 
	['ShootWeaponEntityComp|ShotGunVerticalSpread'] = 'Weapon [散弹枪垂直散布-ShotGunVerticalSpread]', 
	['ShootWeaponEntityComp|ShotGunHorizontalSpread'] = 'Weapon [散弹枪水平散布-ShotGunHorizontalSpread]', 
	['ShootWeaponEntityComp|GameDeviationFactor'] = 'Weapon [所有散布因子-GameDeviationFactor]', 
	['ShootWeaponEntityComp|ScopeJumpDeviationFactor'] = 'Weapon [开镜跳跃散布因子-ScopeJumpDeviationFactor]', 
	['ShootWeaponEntityComp|ScopeFallingDeviationFactor'] = 'Weapon [开镜Falling散布因子-ScopeFallingDeviationFactor]', 
	['ShootWeaponEntityComp|DeviationFactorModifier'] = 'Weapon [最终散布修改参数-DeviationFactorModifier]', 
	['ShootWeaponEntityComp|WeaponAimInTime'] = 'Weapon [枪械开镜速度-WeaponAimInTime]', 
	['ShootWeaponEntityComp|SightType'] = 'Weapon [倍镜类别-SightType]', 
	['ShootWeaponEntityComp|RecoilKickADS'] = 'Weapon [开镜开火后坐力动画表现系数-RecoilKickADS]', 
	['ShootWeaponEntityComp|AnimationKick'] = 'Weapon [开火抖动幅度-AnimationKick]', 
	['ReloadTimeFactorWrapper'] = 'Weapon [UGC换弹时间影响因子-ReloadTimeFactorWrapper]', 
	['SwitchTimeFactorWrapper'] = 'Weapon [UGC切枪时间影响因子-SwitchTimeFactorWrapper]', 
	['ShootIntervalFactorWrapper'] = 'Weapon [UGC攻击间隔影响因子-ShootIntervalFactorWrapper]', 
	['RecoilFactorWrapper'] = 'Weapon [UGC后坐力影响因子-RecoilFactorWrapper]', 
	['DeviationFactorWrapper'] = 'Weapon [UGC散布影响因子-DeviationFactorWrapper]', 
	['BaseImpactDamageWrapper'] = 'Weapon [UGC子弹基础伤害-BaseImpactDamageWrapper]', 
	['MinimumImpactDamageWrapper'] = 'Weapon [UGC子弹最低伤害-MinimumImpactDamageWrapper]', 
	['BulletFireSpeedWrapper'] = 'Weapon [UGC子弹飞行速度-BulletFireSpeedWrapper]', 
	['BulletRangeWrapper'] = 'Weapon [UGC最大射程-BulletRangeWrapper]', 
	['MaxBulletNumInBarrelWrapper'] = 'Weapon [UGC一次拉栓子弹装填数量-MaxBulletNumInBarrelWrapper]', 
	['MaxBulletNumInOneClipWrapper'] = 'Weapon [UGC弹匣容量-MaxBulletNumInOneClipWrapper]', 
	['AutoShootIntervalWrapper'] = 'Weapon [UGC全自动射击间隔-AutoShootIntervalWrapper]', 
	['BurstShootCDWrapper'] = 'Weapon [UGC连发射击间隔-BurstShootCDWrapper]', 
	['BurstShootBulletsNumWrapper'] = 'Weapon [UGC连发数量-BurstShootBulletsNumWrapper]', 
	['BurstShootIntervalWrapper'] = 'Weapon [UGC连发子弹间隔-BurstShootIntervalWrapper]', 

---------------------------------------------------------

	['CurrentHP'] = 'Vehicle [当前血量-CurrentHP]', 
	['MaxHP'] = 'Vehicle [最大血量-MaxHP]', 
	['CurrentFuel'] = 'Vehicle [当前油量-CurrentFuel]', 
	['MaxFuel'] = 'Vehicle [最大油量-MaxFuel]', 
	['FuelConsumeFactor'] = 'Vehicle [耗油系数-FuelConsumeFactor]', 
	['ImpactAbsorption'] = 'Vehicle [撞车时对载具冲量吸收-ImpactAbsorption]', 
	['ImpactAbsorptionPassenger'] = 'Vehicle [撞车时对乘客冲量吸收-ImpactAbsorptionPassenger]', 
	['HitDamagePassengerMaxHP'] = 'Vehicle [撞车时对乘客伤害上限-HitDamagePassengerMaxHP]', 
	['ExplosionBaseDamage'] = 'Vehicle [载具爆炸基础伤害-ExplosionBaseDamage]', 
	['ExplosionMinimumDamage'] = 'Vehicle [载具爆炸最小伤害-ExplosionMinimumDamage]', 
	['FuelConsumptionModifierBoost'] = 'Vehicle [加速油耗系数-FuelConsumptionModifierBoost]', 
	['BoostModifier'] = 'Vehicle [加速动力系数(不同载具动力表达会有所区别)-BoostModifier]', 
	['LinearDamping'] = 'Vehicle [线性阻尼(影响陆地载具和船)-LinearDamping]', 
	['AngularDamping'] = 'Vehicle [旋转阻尼(影响陆地载具和船)-AngularDamping]', 
	['MaxAcceleration'] = 'Vehicle [最大加速度(仅影响船载具)-MaxAcceleration]', 
	['StartAccelerationRate'] = 'Vehicle [加速度增加速率(仅影响船载具)-StartAccelerationRate]', 
	['BackwardForceScale'] = 'Vehicle [倒车时加速度缩放值(仅影响船载具)-BackwardForceScale]', 
	['MaxRotationYawAngle'] = 'Vehicle [最大转向角(仅影响船载具)-MaxRotationYawAngle]', 
	['MaxVelocity'] = 'Vehicle [最大速度限制(0表示无限速，仅影响船载具)-MaxVelocity]', 
	['HitDamageBase'] = 'Vehicle [撞人基础伤害-HitDamageBase]', 
}; 

---@enum UGCCustomGameAttributeType
UGCCustomGameAttributeType = { 
}; 

UGCCustomGameAttributeTypeCommentMap = { 
}; 

